### ISSUE TITLE
Can't start playing video in Tronsmart T428 (Android mini PC)

### ISSUE THREAD

**Issue by cnxsoft** [mauimauer/cheapcast#5]
The application installs just fine, and the device is detected in YouTube. So I can press the Cast button on the smartphone, and CheapCast apps will show up with video information at the top, but the video will not start playing.

**Comment by cnxsoft** [comment]
Here's the logcat between the srtart and the time I get the message "Playing your video on CheapCast is taking an unusually long time" in YouTube App:

E/WifiHW  ( 1640):  
E/WifiHW  ( 1640): EDWARD:is_primary_interface: line=128 ifname: wlan0 , primar 
D/SSDP    ( 3300): Responding to 192.168.0.107  
E/WifiHW  ( 1640):  
E/WifiHW  ( 1640): EDWARD:is_primary_interface: line=128 ifname: wlan0 , primar 
D/CheapCastService( 3300): GET /ssdp/device-desc.xml from 192.168.0.107, com.go)
D/CheapCastService( 3300): GET /apps/YouTube  
D/SSDP    ( 3300): Responding to 192.168.0.107  
D/SSDP    ( 3300): Responding to 192.168.0.107  
E/WifiHW  ( 1640):  
E/WifiHW  ( 1640): EDWARD:is_primary_interface: line=128 ifname: wlan0 , primar 
E/WifiHW  ( 1640):  
E/WifiHW  ( 1640): EDWARD:is_primary_interface: line=128 ifname: wlan0 , primar 
E/WifiHW  ( 1640):  
E/WifiHW  ( 1640): EDWARD:is_primary_interface: line=128 ifname: wlan0 , primar 
D/SSDP    ( 3300): Responding to 192.168.0.107  
D/CheapCastService( 3300): GET /ssdp/device-desc.xml from 192.168.0.107, com.go)
D/CheapCastService( 3300): GET /apps/YouTube  
D/SSDP    ( 3300): Responding to 192.168.0.107  
D/SSDP    ( 3300): Responding to 192.168.0.107  
E/WifiHW  ( 1640):  
E/WifiHW  ( 1640): EDWARD:is_primary_interface: line=128 ifname: wlan0 , primar 
D/dalvikvm( 3300): GC_CONCURRENT freed 537K, 16% free 4309K/5072K, paused 2ms+2s
E/WifiHW  ( 1640):  
E/WifiHW  ( 1640): EDWARD:is_primary_interface: line=128 ifname: wlan0 , primar 
E/WifiHW  ( 1640):  
E/WifiHW  ( 1640): EDWARD:is_primary_interface: line=128 ifname: wlan0 , primar 
D/SSDP    ( 3300): Responding to 192.168.0.107  
D/CheapCastService( 3300): GET /ssdp/device-desc.xml from 192.168.0.107, com.go)
D/CheapCastService( 3300): GET /apps/YouTube  
D/CastActivity( 3281): https://www.youtube.com/tv#/watch?v=pfWQR8GXRNU&mode=trad
E/WifiHW  ( 1640):

**Comment by cnxsoft** [comment]
Screenshots about the issues

This is what I see in the device:
http://www.cnx-software.com/wp-content/uploads/2013/08/CheapCast_YouTube_Video_T428.jpg

This is what shows up in the phone after a while:
http://www.cnx-software.com/wp-content/uploads/2013/08/YouTube_CheapCast_TimeOut.jpg

I have the same problem with Wandboard Quad (Android 4.2.2 image).

**Comment by cnxsoft** [comment]
Fixed with version 0.3.6

**Comment by ghost** [comment]
Just checked with version 4.2.2 (original ROM) and its not working for me. Also tried a Nexus ROM, Finless ROM and Hybrid Firmware ROM.

All these roms gives me a gray screen with no youtube. Also check if i had the last Youtubeversion and updated, disabled the older version but still no luck.
